### ISSUE TITLE
Allow domains to be passed in too

### ISSUE THREAD

**Issue by tandrewnichols** [bnurbekov/company-email-validator#1]
Hey, I'm looking at the implementation for `isCompanyEmail` and it is expecting a _full_ email address. However, in our use case we have only the domain, and we just want to see if it's in the list. Would you be open to a PR that does something like

```
const isFullAddress = email.includes('@');
if (isFullAddress) {
  // validate the email
}

const domain = isFullAddress ? email.split('@')[1] : email;
```

?

That way both full emails _and_ domains could be passed in.

Alternatively, I could make a separate function, `isCompanyDomain` or something.

**Comment by bnurbekov** [comment]
Hi @tandrewnichols . Yes, absolutely - I am open. I think having a separate function `isCompanyDomain` might be a good way to do.
