### ISSUE TITLE
How about relay services like duck.com

### ISSUE THREAD

**Issue by anupriya17** [bnurbekov/company-email-validator#5]
Thanks for the wonderful lib. There're many email disposable services, can we block some default services like duck duck go.

- **duck.com** -- DuckDuckGo

Seems you already covered icloud private relay. I love Duck's privacy but at the same time we want to avoid noise as well

**Comment by bnurbekov** [comment]
Thank you for your suggestion and sorry for the delay. I will add duck.com.
