### ISSUE TITLE
Reference error with `free_email_provider_set` in TS

### ISSUE THREAD

**Issue by rudeluv** [bnurbekov/company-email-validator#6]
Hi there, thanks for the package! 

I ran into an error while trying to use it in a Typescript monorepo. It seems that the implicit declaration of `free_email_provider_set` is causing issues. Not sure if it's TS/es-build related but explicitly declaring it fixes the issue and all tests pass. 

```
ERROR	ReferenceError: free_email_provider_set is not defined
at ../../node_modules/company-email-validator/free_email_provider_domains.js
```

I just declared it like `const free_email_provider_set = new Set(free_email_provider_domains.split("\n"))` and that worked. 

I can push a PR up with a fix if this seems like a legit issue.

**Comment by uzmo** [comment]
ReferenceError: free_email_provider_set is not defined
I also ran into this error.

**Comment by bnurbekov** [comment]
Hi @rudeluv, thank you for your report and help. Please, could you create a PR for this issue, as you suggested?

**Comment by rudeluv** [comment]
@bnurbekov sure thing, this PR should fix it ☝️.
